from typing import List, Optional
from sqlalchemy import String, Boolean
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.core.database import Base
from app.models.base import TimestampMixin, UUIDPrimaryKeyMixin


class User(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    User model representing registered system accounts.
    """
    __tablename__ = "users"

    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        index=True,
        nullable=False,
        doc="Unique email address for authentication and notifications"
    )
    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc="Salted and hashed password"
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean(),
        default=True,
        nullable=False,
        doc="Status flag to enable/disable user accounts"
    )
    is_superuser: Mapped[bool] = mapped_column(
        Boolean(),
        default=False,
        nullable=False,
        doc="Status flag granting administrator permissions"
    )

    # --- Relationships ---
    
    # One-to-One: A user has exactly one professional Profile detail.
    # uselist=False instructs SQLAlchemy to configure a scalar attribute on the parent.
    # cascade="all, delete-orphan" guarantees that when a User is deleted, their associated Profile is also cleaned up.
    profile: Mapped[Optional["Profile"]] = relationship(
        "Profile",
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan",
        doc="One-to-one profile associated with this user"
    )

    # One-to-Many: A user can upload multiple resume configurations.
    resumes: Mapped[List["Resume"]] = relationship(
        "Resume",
        back_populates="user",
        cascade="all, delete-orphan",
        doc="List of resumes uploaded by this user"
    )

    # One-to-Many: A user can generate and save multiple career roadmaps.
    roadmaps: Mapped[List["Roadmap"]] = relationship(
        "Roadmap",
        back_populates="user",
        cascade="all, delete-orphan",
        doc="List of career roadmaps generated by/for this user"
    )

    # Many-to-Many: A user can have multiple skills, and a skill can belong to multiple users.
    # This relation resolved via the "user_skills" association table.
    skills: Mapped[List["Skill"]] = relationship(
        "Skill",
        secondary="user_skills",
        back_populates="users",
        doc="List of professional skills associated with this user"
    )

    # One-to-Many: A user can have multiple career coaching chats.
    career_chats: Mapped[List["CareerChat"]] = relationship(
        "CareerChat",
        back_populates="user",
        cascade="all, delete-orphan",
        doc="List of career coaching chats belonging to this user"
    )

    # One-to-Many: A user can save multiple ATS analyses.
    ats_analyses: Mapped[List["ATSAnalysis"]] = relationship(
        "ATSAnalysis",
        back_populates="user",
        cascade="all, delete-orphan",
        doc="List of ATS analyses saved by this user"
    )


