import uuid
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.schemas.roadmap import RoadmapCreate, RoadmapResponse, RoadmapGenerateRequest, RoadmapGenerateResponse
from app.schemas.roadmap_task import RoadmapTaskCreate, RoadmapTaskResponse
from app.services.roadmap_service import roadmap_service
from app.models.user import User
from app.api.deps import get_current_user
from app.utils.exceptions import EntityNotFoundError, ForbiddenError

router = APIRouter()


@router.post(
    "",
    response_model=RoadmapResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate a career roadmap"
)
def create_roadmap(
    user_id: uuid.UUID,
    roadmap_in: RoadmapCreate,
    db: Session = Depends(get_db)
) -> RoadmapResponse:
    """
    Creates a new career pathway roadmap for a user.
    """
    try:
        return roadmap_service.create_roadmap(db, user_id=user_id, roadmap_in=roadmap_in)
    except EntityNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e)
        )


@router.get(
    "/{roadmap_id}",
    response_model=RoadmapResponse,
    status_code=status.HTTP_200_OK,
    summary="Retrieve career roadmap details"
)
def get_roadmap(
    roadmap_id: uuid.UUID,
    db: Session = Depends(get_db)
) -> RoadmapResponse:
    """
    Queries details for a generated career roadmap including all sequenced tasks.
    """
    try:
        return roadmap_service.get_roadmap(db, roadmap_id=roadmap_id)
    except EntityNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e)
        )


@router.post(
    "/{roadmap_id}/tasks",
    response_model=RoadmapTaskResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Add milestone task to roadmap"
)
def create_task(
    roadmap_id: uuid.UUID,
    task_in: RoadmapTaskCreate,
    db: Session = Depends(get_db)
) -> RoadmapTaskResponse:
    """
    Adds a new learning task directly under the specified career roadmap track.
    """
    try:
        return roadmap_service.create_task(db, roadmap_id=roadmap_id, task_in=task_in)
    except EntityNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e)
        )


@router.patch(
    "/tasks/{task_id}",
    response_model=RoadmapTaskResponse,
    status_code=status.HTTP_200_OK,
    summary="Modify task completion status"
)
def update_task_status(
    task_id: uuid.UUID,
    status: str = Query(..., description="The new status of the task (e.g. pending, in_progress, completed)"),
    db: Session = Depends(get_db)
) -> RoadmapTaskResponse:
    """
    Updates the completion status state parameter of a single roadmap milestone task.
    """
    try:
        return roadmap_service.update_task_status(db, task_id=task_id, status=status)
    except EntityNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e)
        )


@router.get(
    "",
    response_model=List[RoadmapResponse],
    status_code=status.HTTP_200_OK,
    summary="List user career roadmaps"
)
def get_user_roadmaps(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> List[RoadmapResponse]:
    """
    List all career roadmaps generated by the current user.
    """
    return roadmap_service.get_roadmaps_for_user(db, user_id=current_user.id)


@router.post(
    "/generate",
    response_model=RoadmapGenerateResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate personalized career roadmap from resume"
)
def generate_roadmap(
    req: RoadmapGenerateRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> RoadmapGenerateResponse:
    """
    Generates a personalized career roadmap track using candidates' parsed resume skills and goal target role.
    """
    try:
        db_roadmap = roadmap_service.generate_roadmap_for_user(
            db, user_id=current_user.id, resume_id=req.resume_id, target_role=req.target_role
        )
        return RoadmapGenerateResponse(
            roadmap_id=db_roadmap.id,
            title=db_roadmap.title,
            description=db_roadmap.description or "",
            tasks=db_roadmap.tasks,
            milestones=db_roadmap.milestones
        )
    except EntityNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e)
        )
    except ForbiddenError as e:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=str(e)
        )


@router.delete(
    "/{roadmap_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a career roadmap"
)
def delete_roadmap(
    roadmap_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> None:
    """
    Deletes the specified career roadmap track. Enforces ownership verification.
    """
    try:
        roadmap_service.delete_roadmap(db, roadmap_id=roadmap_id, user_id=current_user.id)
    except EntityNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e)
        )
    except ForbiddenError as e:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=str(e)
        )


